### ISSUE TITLE
Broken delayed job monitoring

### ISSUE THREAD

**Issue by johnsyweb** [scoutapp/scout-plugins#199]
"Use arel for monitor_delayed_jobs.rb" #181 has broken delayed job monitoring on our hosts

# The failure message:

```
NoMethodError: undefined method `where' for # 
/usr/local/rbenv/versions/ree-1.8.7-2011.12/lib/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/base.rb:1998:in `method_missing' 
Delayed Job:50:in `build_report' 
/usr/local/rbenv/versions/ree-1.8.7-2011.12/lib/ruby/gems/1.8/gems/scout-5.5.3/lib/scout/plugin.rb:220:in `run' 
/usr/local/rbenv/versions/ree-1.8.7-2011.12/lib/ruby/gems/1.8/gems/scout-5.5.3/lib/scout/server.rb:367:in `process_plugin' 
/usr/local/rbenv/versions/ree-1.8.7-2011.12/lib/ruby/1.8/timeout.rb:67:in `timeout' 
/usr/local/rbenv/versions/ree-1.8.7-2011.12/lib/ruby/gems/1.8/gems/scout-5.5.3/lib/scout/server.rb:366:in `process_plugin' 
/usr/local/rbenv/versions/ree-1.8.7-2011.12/lib/ruby/gems/1.8/gems/scout-5.5.3/lib/scout/server.rb:270:in `run_plugins_by_plan' 
/usr/local/rbenv/versions/ree-1.8.7-2011.12/lib/ruby/gems/1.8/gems/scout-5.5.3/lib/scout/server.rb:268:in `each' 
/usr/local/rbenv/versions/ree-1.8.7-2011.12/lib/ruby/gems/1.8/gems/scout-5.5.3/lib/scout/server.rb:268:in `run_plugins_by_plan' 
/usr/local/rbenv/versions/ree-1.8.7-2011.12/lib/ruby/gems/1.8/gems/scout-5.5.3/lib/scout/command/run.rb:43:in `run' 
/usr/local/rbenv/versions/ree-1.8.7-2011.12/lib/ruby/gems/1.8/gems/scout-5.5.3/lib/scout/command.rb:154:in `dispatch' 
/usr/local/rbenv/versions/ree-1.8.7-2011.12/lib/ruby/gems/1.8/gems/scout-5.5.3/bin/scout:10 
/usr/local/rbenv/versions/ree-1.8.7-2011.12/bin/scout:19:in `load' 
/usr/local/rbenv/versions/ree-1.8.7-2011.12/bin/scout:19
```

# An example in IRB:

## Setup

```
irb(main):010:0* ONE_DAY    = 60 * 60 * 24
irb(main):011:0> 
irb(main):012:0* require 'thread'
irb(main):013:0> # IMPORTANT! Requiring Rubygems is NOT a best practice. See http://scoutapp.com/info/creating_a_plugin#libraries
irb(main):014:0* # This plugin is an exception because we to subclass ActiveRecord::Base before the plugin's build_report method is run.
irb(main):015:0* require 'rubygems' 
irb(main):016:0> require 'active_record'
irb(main):017:0> class DelayedJob < ActiveRecord::Base; end
irb(main):018:0> DelayedJob.default_timezone = :utc
irb(main):019:0> 
irb(main):020:0* app_path = option(:path_to_app)
irb(main):021:0> 
irb(main):022:0* # Ensure path to db config provided
irb(main):023:0* if !app_path or app_path.empty?
irb(main):024:1>   return error("The path to the Rails Application wasn't provided.","Please provide the full path to the Rails Application (ie - /var/www/apps/APP_NAME/current)")
irb(main):025:1> end
irb(main):026:0> 
irb(main):027:0* db_config_path = app_path + '/config/database.yml'
irb(main):028:0> 
irb(main):029:0* if !File.exist?(db_config_path)
irb(main):030:1>   return error("The database config file could not be found.", "The database config file could not be found at: #{db_config_path}. Please ensure the path to the Rails Application is correct.")
irb(main):031:1> end
irb(main):032:0> 
irb(main):033:0* db_config = YAML::load(ERB.new(File.read(db_config_path)).result)
irb(main):034:0> ActiveRecord::Base.establish_connection(db_config[option(:rails_env)])
irb(main):035:0> 
irb(main):036:0* report_hash = Hash.new
irb(main):037:0> 
irb(main):038:0* # ALl jobs
irb(main):039:0* report_hash[:total]     = DelayedJob.count
irb(main):040:0> puts report_hash.inspect
{:total=>602}
```

So we're getting valid data. 

## And now for AREL:

```
irb(main):041:0> 
irb(main):042:0* report_hash[:running]   = DelayedJob.where('locked_at IS NOT NULL AND failed_at IS NULL').count
NoMethodError: undefined method `where' for #<Class:0x1ff12d8>
	from /usr/local/rbenv/versions/ree-1.8.7-2011.12/lib/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/base.rb:1998:in `method_missing'
	from (irb):42
	from :0
irb(main):043:0> puts report_hash.inspect
{:total=>602}
```

## Old version
```
irb(main):044:0> 
irb(main):045:0* report_hash[:running]   = DelayedJob.count(:conditions => 'locked_at IS NOT NULL AND failed_at IS NULL')
irb(main):046:0> puts report_hash.inspect
{:running=>14, :total=>602}
irb(main):047:0> 
```

**Comment by dlanderson** [comment]
Ah, sorry about that @johnsyweb - the reason it was switched to AREL is because activerecord 4.1 dropped support for the old query format so it was preventing the plugin running on activerecord >= 4.1 servers. Mind sending us an email to support@ pointing to which of your servers are running this plugin? We can see what options we have for getting it working again.

**Comment by dlanderson** [comment]
Fixed in PR https://github.com/scoutapp/scout-plugins/pull/200
